name: release

on: [push]

jobs:

  build:
    
    runs-on: windows-latest
        
    steps:
      # First of all, we clone the repo using the `checkout` action.
      - name: Checkout  
        uses: actions/checkout@v4

      # Use the `arduino/setup-arduino-cli` action to install 
      # and configure the Arduino CLI on the system.
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      # Install platform
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
      # Compile sketch using the fully qualified board name ( FQBN )
      - name: Compile sketch
        run: arduino-cli compile --fqbn -e arduino:avr:uno ./blink
        
      # Upload artifact
      - name: Upload artifact   
        uses: actions/upload-artifact@v1
        with:
          name: blink.ino.hex
          path: releases/blink.ino.hex 
          
      # Publish release    
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "releases/blink.ino.hex"
          tag: "release"
          token: ${{ secrets.GITHUB_TOKEN }}  
